version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore:"
    labels:
      - "dependabot: ecosystem : github actions"
      - "dependabot: dependencies"
    assignees:
      - "Lupraxus"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore:"
    labels:
      - "dependabot: ecosystem : ruby"
      - "dependabot: dependencies"
    assignees:
      - "Lupraxus"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore:"
    labels:
      - "dependabot: ecosystem : github actions"
      - "dependabot: dependencies"
    assignees:
      - "Lupraxus"
    ignore:
      # These are peer deps of Cargo and should not be automatically bumped
      - dependency-name: "semver"
      - dependency-name: "crates-io"
    rebase-strategy: "disabled"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore:"
    labels:
      - "dependabot: ecosystem : php"
      - "dependabot: dependencies"
    assignees:
      - "Lupraxus"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore:"
    labels:
      - "dependabot: ecosystem : docker"
      - "dependabot: dependencies"
    assignees:
      - "Lupraxus"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore:"
    labels:
      - "dependabot: ecosystem : go"
      - "dependabot: dependencies"
    assignees:
      - "Lupraxus"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "07:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore:"
    labels:
      - "dependabot: ecosystem : npm"
      - "dependabot: dependencies"
    assignees:
      - "Lupraxus"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:30"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore:"
    labels:
      - "dependabot: ecosystem : pip"
      - "dependabot: dependencies"
    assignees:
      - "Lupraxus"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore:"
    labels:
      - "dependabot: ecosystem : terraform"
      - "dependabot: dependencies"
    assignees:
      - "Lupraxus"
