blank_issues_enabled: false

contact_links:
  - name: ğŸ›¡ï¸ Security disclosure
    url: https://github.com/the-lupaxa-project/.github/blob/master/SECURITY.md
    about: Found a vulnerability? Please review our Security Policy.

  - name: â˜• Support the project
    url: https://ko-fi.com/thelupaxaproject
    about: Show your support for The Lupaxa Project and help sustain open-source development.

  - name: ğŸŒ Visit our website
    url: https://thelupaxaproject.org
    about: Learn more about The Lupaxa Project and our philosophy.
