name: Stale Issue & PR Handler

on:
  schedule:
    - cron: "35 5 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    name: Run Stale Issue & PR Handler
    uses: ./.github/workflows/reusable-stale.yml

  status-check:
    name: Check Lint Job Statuses
    needs:
      - stale

    # ðŸ”´ IMPORTANT: this is a *job-level* uses, not under steps:
    uses: ./.github/workflows/reusable-check-jobs-status.yml
    with:
      jobs_json: ${{ toJson(needs) }}
