name: Purge Deprecated Workflow Runs

on:
  workflow_dispatch:

  schedule:
    - cron: '33 3 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

jobs:
  purge-deprecated-workflows:
    name: Run Purge Deprecated Workflow Runs (Reusable)
    uses: ./.github/workflows/reusable-purge-deprecated-workflow-runs.yml

  status-check:
    name: Check Lint Job Statuses
    needs:
      - purge-deprecated-workflows
    if: always()
    # ðŸ”´ IMPORTANT: this is a *job-level* uses, not under steps:
    uses: ./.github/workflows/reusable-check-jobs-status.yml
    with:
      jobs_json: ${{ toJson(needs) }}

