name: Check Jobs Status Summary

on:
  workflow_call:
    inputs:
      jobs_json:
        description: "JSON representation of the 'needs' context from the caller workflow."
        required: true
        type: string

permissions:
  contents: read

jobs:
  check-jobs-status:
    name: Pipeline Job Summary
    runs-on: ubuntu-latest

    steps:
      - name: Run central check-jobs.sh
        run: |
          bash <(curl -fsSL \
            "https://raw.githubusercontent.com/the-lupaxa-project/.github/master/.github/scripts/check-jobs.sh") \
            '${{ inputs.jobs_json }}'
