name: Reusable Docs Lint (Markdown + YAML)

on:
  workflow_call:
    inputs:
      md_globs:
        description: 'Comma-separated globs for Markdown files'
        required: false
        type: string
        default: "**/*.md"
      yml_globs:
        description: 'Comma-separated globs for YAML files'
        required: false
        type: string
        default: "**/*.yml,**/*.yaml"
    secrets:
      GH_TOKEN:
        required: false

jobs:
  markdown:
    uses: the-lupaxa-project/.github/.github/workflows/reuse-markdown-lint.yml@main
    with:
      globs: ${{ inputs.md_globs }}
    secrets: inherit

  yaml:
    uses: the-lupaxa-project/.github/.github/workflows/reuse-yaml-lint.yml@main
    with:
      globs: ${{ inputs.yml_globs }}
    secrets: inherit