name: Reusable Markdown Lint

on:
  workflow_call:
    inputs:
      globs:
        description: 'Comma-separated globs for Markdown files'
        required: false
        type: string
        default: "**/*.md"
    secrets:
      GH_TOKEN:
        required: false

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903  # v6.0.0
        with:
          node-version: 'lts/*'

      - name: Install markdownlint-cli
        run: npm install --global markdownlint-cli

      - name: Lint Markdown
        run: |
          IFS=',' read -ra GLOBS <<< "${{ inputs.globs }}"
          markdownlint "${GLOBS[@]}"